import { GoogleGenAI, Type, Schema } from "@google/genai";
import { AnalysisResult } from "../types";

// Initialize the Gemini API client
// Note: process.env.API_KEY is injected by the environment
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const analyzeText = async (text: string): Promise<AnalysisResult> => {
  if (!text || text.length < 50) {
    throw new Error("Text is too short to analyze accurately. Please provide at least 50 characters.");
  }

  // Schema definition for structured JSON output
  const analysisSchema: Schema = {
    type: Type.OBJECT,
    properties: {
      humanScore: {
        type: Type.NUMBER,
        description: "Percentage probability (0-100) that the text is written by a human.",
      },
      aiScore: {
        type: Type.NUMBER,
        description: "Percentage probability (0-100) that the text is generated by AI.",
      },
      verdict: {
        type: Type.STRING,
        description: "A short verdict title (e.g., 'Likely Human', 'Possibly AI-Generated').",
      },
      explanation: {
        type: Type.STRING,
        description: "A comprehensive paragraph explaining the reasoning behind the score.",
      },
      aiSegments: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            text: { type: Type.STRING, description: "The specific sentence or paragraph identified as AI-generated." },
            reason: { type: Type.STRING, description: "Why this specific part looks like AI (e.g., 'Perfect grammar, low burstiness')." }
          }
        },
        description: "List of specific text segments that appear to be AI-generated.",
      },
      typos: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            text: { type: Type.STRING, description: "The word with the typo." },
            suggestion: { type: Type.STRING, description: "Corrected spelling." },
            context: { type: Type.STRING, description: "Short sentence fragment showing the typo." }
          }
        },
        description: "List of spelling or grammatical errors found.",
      },
      linguisticPatterns: {
        type: Type.ARRAY,
        items: { type: Type.STRING },
        description: "List of linguistic features observed.",
      },
      toneAnalysis: {
        type: Type.STRING,
        description: "Description of the emotional tone.",
      },
      methodology: {
        type: Type.STRING,
        description: "Explanation of the resources/logic used (e.g., Perplexity, Burstiness, Training Data comparisons).",
      }
    },
    required: ["humanScore", "aiScore", "verdict", "explanation", "aiSegments", "typos", "linguisticPatterns", "toneAnalysis", "methodology"],
  };

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: `You are a forensic linguistic AI detector. Analyze the text below.

      1. **Detection**: Determine if the text is AI-generated or Human.
      2. **AI Segments**: extract specific sentences/paragraphs that look robotic, have low perplexity, or lack human nuance.
      3. **Typos**: Identify spelling and grammar mistakes (Humans make typos, AI rarely does).
      4. **Methodology**: Explain that the analysis relies on 'Perplexity' (randomness) and 'Burstiness' (sentence variation) comparisons against Large Language Model probability distributions.

      Text to analyze:
      """
      ${text.substring(0, 12000)} 
      """`,
      config: {
        responseMimeType: "application/json",
        responseSchema: analysisSchema,
        temperature: 0.1,
      },
    });

    if (!response.text) {
      throw new Error("No response received from analysis engine.");
    }

    const result = JSON.parse(response.text) as AnalysisResult;
    return result;

  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    throw new Error("Failed to analyze the document. Please try again.");
  }
};